Repository lunarway/postgresql-controller, pull requests merged in 2024-06, with the labels that each got.

#293 chore(deps): update golang docker tag to v1.22.4
  .github/workflows/lint.yaml
  Dockerfile
Labels: dependencies

#294 feat/update kubebuilder
  Makefile
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/postgresql.lunar.tech_postgresqldatabases.yaml
  config/crd/bases/postgresql.lunar.tech_postgresqlhostcredentials.yaml
  config/crd/bases/postgresql.lunar.tech_postgresqlusers.yaml
  config/rbac/role.yaml
  go.sum
Labels: minor

#296 feat: update kubebuilder v3 -> v4
  Dockerfile
  Makefile
  PROJECT
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/postgresql.lunar.tech_postgresqldatabases.yaml
  config/crd/bases/postgresql.lunar.tech_postgresqlhostcredentials.yaml
  config/crd/bases/postgresql.lunar.tech_postgresqlusers.yaml
  go.mod
  go.sum
  hack/boilerplate.go.txt
  internal/config/config.go
  internal/config/config_test.go
  internal/controller/postgresqldatabase_controller.go
  internal/controller/postgresqldatabase_controller_test.go
  internal/controller/postgresqlhostcredentials_controller.go
  internal/controller/postgresqluser_controller.go
  internal/controller/postgresqluser_controller_test.go
  pkg/iam/iam_test.go
  test/test.go
Labels: minor

#297 feat: enable buildx again
  .github/workflows/release.yaml
  Makefile
Labels: patch

#295 feat: add service user crd
  PROJECT
  api/v1alpha1/postgresqlserviceuser_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/postgresql.lunar.tech_postgresqlserviceusers.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_postgresqlserviceusers.yaml
  config/crd/patches/webhook_in_postgresqlserviceusers.yaml
  config/rbac/postgresqlserviceuser_editor_role.yaml
  config/rbac/postgresqlserviceuser_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/postgresql_v1alpha1_postgresqlserviceuser.yaml
  go.mod
  go.sum
  internal/controller/postgresqlserviceuser_controller.go
  internal/controller/suite_test.go
Labels: minor

#265 fix(deps): update external go packages
  go.mod
  go.sum
Labels: dependencies
